---
# Simple gRPC Debug Pod
# Use this for basic gRPC service testing within the cluster
apiVersion: v1
kind: Pod
metadata:
  name: grpc-debug
  namespace: default
  labels:
    app: grpc-debug
spec:
  containers:
  - name: grpc-debug
    image: grpc-debug:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
  restartPolicy: Never

---
# gRPC Debug Pod with Proto Files from ConfigMap
# Use this when your gRPC service doesn't support server reflection
apiVersion: v1
kind: ConfigMap
metadata:
  name: grpc-protos
  namespace: default
data:
  # Add your .proto files here
  example.proto: |
    syntax = "proto3";
    package example;

    service ExampleService {
      rpc GetExample(ExampleRequest) returns (ExampleResponse) {}
    }

    message ExampleRequest {
      string id = 1;
    }

    message ExampleResponse {
      string id = 1;
      string name = 2;
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: grpc-debug-with-protos
  namespace: default
  labels:
    app: grpc-debug
    feature: proto-files
spec:
  containers:
  - name: grpc-debug
    image: grpc-debug:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: protos
      mountPath: /home/debugger/protos
      readOnly: true
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: protos
    configMap:
      name: grpc-protos
  - name: tmp
    emptyDir: {}
  restartPolicy: Never

---
# gRPC Debug Pod with mTLS Support
# Use this for testing gRPC services with mutual TLS (e.g., service mesh)
apiVersion: v1
kind: Pod
metadata:
  name: grpc-debug-mtls
  namespace: default
  labels:
    app: grpc-debug
    feature: mtls
spec:
  containers:
  - name: grpc-debug
    image: grpc-debug:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    env:
    - name: GRPC_DEFAULT_SSL_ROOTS_FILE_PATH
      value: /certs/ca.crt
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: certs
      mountPath: /certs
      readOnly: true
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: certs
    secret:
      secretName: grpc-client-certs  # Create this secret with your TLS certs
      optional: true
  - name: tmp
    emptyDir: {}
  restartPolicy: Never

---
# gRPC Debug Pod with grpcui Web Interface
# Exposes port 8080 for accessing the gRPC UI
apiVersion: v1
kind: Pod
metadata:
  name: grpc-debug-ui
  namespace: default
  labels:
    app: grpc-debug
    feature: web-ui
spec:
  containers:
  - name: grpc-debug
    image: grpc-debug:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args:
    - -c
    - |
      echo "Starting grpcui on port 8080..."
      echo "Access via: kubectl port-forward grpc-debug-ui 8080:8080"
      # Replace with your gRPC service endpoint
      # grpcui -plaintext -bind 0.0.0.0 -port 8080 my-grpc-service:50051
      while true; do sleep 3600; done
    ports:
    - containerPort: 8080
      name: grpcui
      protocol: TCP
    resources:
      requests:
        memory: "64Mi"
        cpu: "20m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  volumes:
  - name: tmp
    emptyDir: {}
  restartPolicy: Never

---
# Service for gRPC UI Pod
apiVersion: v1
kind: Service
metadata:
  name: grpc-debug-ui
  namespace: default
spec:
  selector:
    app: grpc-debug
    feature: web-ui
  ports:
  - name: grpcui
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP

---
# gRPC Debug Pod for Cross-Namespace Testing
# Deploy this in different namespaces to test network policies
apiVersion: v1
kind: Pod
metadata:
  name: grpc-debug
  namespace: test-namespace  # Change this to your target namespace
  labels:
    app: grpc-debug
    role: network-tester
spec:
  containers:
  - name: grpc-debug
    image: grpc-debug:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    resources:
      requests:
        memory: "32Mi"
        cpu: "10m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
        - ALL
  restartPolicy: Never

---
# Job for One-Time gRPC Load Testing
# Use this to run ghz benchmarks as a Kubernetes Job
apiVersion: batch/v1
kind: Job
metadata:
  name: grpc-load-test
  namespace: default
spec:
  template:
    metadata:
      labels:
        app: grpc-load-test
    spec:
      containers:
      - name: grpc-debug
        image: grpc-debug:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Running gRPC load test..."
          # Example: ghz --insecure --call package.Service/Method \
          #   -d '{"name":"test"}' -c 10 -n 1000 my-service:50051
          echo "Load test completed"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "1000m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      restartPolicy: Never
  backoffLimit: 3
